### ISSUE TITLE
Possibility for adding unique QA data attribute to components

### ISSUE THREAD

**Issue by lievenvg** [digipolisantwerp/acpaas-ui_react#100]
## Is your feature request related to a problem? Please describe.

For test automation purposes, having a unique selector on your components can be very helpful. At this point it's not possible to add a custom prop.

## Describe the solution you'd like

A possible solution could be to add a `dataQa` prop to each component.
E.g.:
`render() {
    const { children, "data-qa": dataQa } = this.props;
    const { isOpen } = this.state;

    return (
      <div
        role="button"
        tabIndex="0"
        data-qa={dataQa}
	...
      >
        { children }
      </div>
);`

## Describe alternatives you've considered

An alternative could be to use the JavaScript spread operator, but perhaps it's not wishful behaviour to accept all types of props.

## Additional context

This is issue is related to the [Test automation guidelines](https://github.com/digipolisantwerp/acpaas-ui_angular/blob/master/TEST_AUTOMATION.md
) of the ACPaaS Angular Component library.

**Comment by TriangleJuice** [comment]
Why not simply using `QA` instead? What's the added value of the data prefix?

**Comment by lievenvg** [comment]
It's opinionated, but as far as I know a custom html attribute without data prefix is [not valid HTML](https://stackoverflow.com/questions/24932391/are-custom-html-attributes-without-data-prefix-a-valid-attribute) and I tried to keep things in line with the ACPaaS Angular library [test automation guidelines](https://github.com/digipolisantwerp/acpaas-ui_angular/blob/master/TEST_AUTOMATION.md).

**Comment by gerturo** [comment]
data-test-*something* (https://ember-test-selectors.com)

**Comment by TriangleJuice** [comment]
I was talking about the React property `dataQa`. It's true that the html part should (and must) be prefixed by `data`, but not the prop.

**Comment by lievenvg** [comment]
Gotcha.
I was following the camelCase convention for DOM properties and attributes in React, but in this case `QA` is valid as well.
`QA` is shorter, so that's fine for me.

**Comment by TriangleJuice** [comment]
`qa` is also fine for me BTW ;-)
