### ISSUE TITLE
UserMenu not usable for employees

### ISSUE THREAD

**Issue by stefanpante** [digipolisantwerp/acpaas-ui_react#129]
The UserMenu used to be usable for employees. 
At the moment, irrelevant links for employees are shown in the menu because the component has no way of knowing if the passed user object is an employee.
## Expected behavior

We should be able to disable the menu for employees or give another predefined list of options.

CC: @tomdillien91

**Comment by stefanpante** [comment]
The properties given in the styleguidist documentation are not up-to-date.

**Comment by TriangleJuice** [comment]
This was fixed in #157
