### ISSUE TITLE
classnames ontbreekt + werkt niet met de standaard CRA setup.

### ISSUE THREAD

**Issue by stefanpante** [digipolisantwerp/acpaas-ui_react#2]

**Comment by jdr66** [comment]
Om te kunnen compilen in webpack.config.js:
exclude: /node_modules/
vervangen door:
exclude: /node_modules\/?!@acpaas-ui.*/



Originele error:

./node_modules/@acpaas-ui/react-components/packages/form/src/TextField/TextField.js
Module parse failed: Unexpected token (12:5)
You may need an appropriate loader to handle this file type.
| };
| 
| type InputStates = "success" | "warning" | "error";
| 
| type Props = {
 @ ./node_modules/@acpaas-ui/react-components/packages/form/src/TextField/index.js 1:0-38 1:0-38
 @ ./node_modules/@acpaas-ui/react-components/packages/form/src/index.j

**Comment by frankdsm** [comment]
@jdr66 kan je nog eens proberen met de laatste versie? Zou opgelost moeten zijn (getest met CRA app)
