### ISSUE TITLE
Modal is broken in styleguide

### ISSUE THREAD

**Issue by jsebrech** [digipolisantwerp/acpaas-ui_react#63]
## Describe the bug

The styleguide's Modal section shows the error "TypeError: Cannot read property 'appElement' of undefined"

## To Reproduce

1. Go to https://digipolisantwerp.github.io/acpaas-ui_react/#modal
2. See error

## Expected behavior

The Modal is shown

## OS (please complete the following information):

 - OS: windows
 - Browser Chrome
 - Version 70

**Comment by HybridFox** [comment]
Fixed in #65

**Comment by jsebrech** [comment]
Error is still shown.

**Comment by TriangleJuice** [comment]
Should be fixed in #119
