### ISSUE TITLE
a-logo.svg in header should be loaded from CDN

### ISSUE THREAD

**Issue by jsebrech** [digipolisantwerp/acpaas-ui_react#72]
## Describe the bug

The Header component specifies that the a-logo svg image is loaded from github.io:

https://a-ui.github.io/core_branding_scss/images/a-logo.svg

This should be published on cdn.antwerpen.be instead. (@TriangleJuice can assist with getting this published.)

**Comment by TriangleJuice** [comment]
http://cdn.antwerpen.be/core_branding_scss/3.1.0/assets/images/a-logo.svg 😉
