### ISSUE TITLE
Custom logo in Header component

### ISSUE THREAD

**Issue by TriangleJuice** [digipolisantwerp/acpaas-ui_react#94]
## Is your feature request related to a problem? Please describe.

I would like to use the Header component in projects that aren't in the Antwerp style. Since the Antwerp logo is always part of the Header component this is not possible.

## Describe the solution you'd like

An optional extra prop to define the logo src.

## Describe alternatives you've considered

A hard-coded header.

## Additional context

N/A

**Comment by tomdillien91** [comment]
@TriangleJuice , heb ik meegenomen voor je in PR van https://github.com/digipolisantwerp/acpaas-ui_react/pull/103/files

**Comment by tomdillien91** [comment]
Toegevoegd in de Header component
